// popup.js - Reads analysis from storage and updates existing HTML elements

const STORAGE_PREFIX = "globemallow_analysis:";
let currentAnalysis = null;

// Metric explanations
const METRIC_EXPLANATIONS = {
  fcp: {
    title: "First Contentful Paint (FCP)",
    description:
      "How quickly the first piece of content appears on screen. Good FCP is under 1.8 seconds. This affects how fast your site feels to users.",
  },
  lcp: {
    title: "Largest Contentful Paint (LCP)",
    description:
      "Time until the largest element (image or text block) is visible. Good LCP is under 2.5 seconds. This is when users see the main content.",
  },
  tbt: {
    title: "Total Blocking Time (TBT)",
    description:
      "How long the page is unresponsive to user input. Lower is better. High TBT means users can't click or scroll smoothly.",
  },
  cls: {
    title: "Cumulative Layout Shift (CLS)",
    description:
      "Measures visual stability - how much elements move around unexpectedly. Good CLS is under 0.1. Prevents frustrating layout jumps.",
  },
  "lazy-loading": {
    title: "Lazy Loading",
    description:
      "Delays loading images until they're needed. This speeds up initial page load and saves bandwidth for images users never see.",
  },
  "modern-images": {
    title: "Modern Image Formats",
    description:
      "WebP and AVIF formats are 25-35% smaller than JPEG/PNG with the same quality. Using modern formats reduces page size significantly.",
  },
  "responsive-images": {
    title: "Responsive Images",
    description:
      "Serves appropriately sized images based on device screen. Mobile users shouldn't download desktop-sized images.",
  },
  "image-compression": {
    title: "Image Compression",
    description:
      "The amount of bytes that could be saved by properly compressing images without visible quality loss.",
  },
  "bundle-size": {
    title: "JavaScript Bundle Size",
    description:
      "Total size of JavaScript files. Larger bundles take longer to download and parse, slowing down your site.",
  },
  "unused-js": {
    title: "Unused JavaScript",
    description:
      "JavaScript code that's downloaded but never executed. Removing this reduces bundle size and improves load time.",
  },
  "css-usage": {
    title: "CSS Usage",
    description:
      "Percentage of CSS actually used on the page. Unused CSS increases file size without benefit.",
  },
  "third-party-scripts": {
    title: "Third-Party Scripts",
    description:
      "External scripts (ads, analytics, widgets). Each one adds loading time and reduces your control over performance.",
  },
  gzip: {
    title: "Compression",
    description:
      "Gzip or Brotli compression reduces file sizes by 60-80%. This is a server setting that dramatically improves load times.",
  },
  minification: {
    title: "Minification",
    description:
      "Removes whitespace and shortens code without changing functionality. Typically reduces file size by 15-25%.",
  },
  https: {
    title: "HTTPS Security",
    description:
      "Encrypted connection that protects user data. Required for many modern web features and trusted by search engines.",
  },
  "browser-caching": {
    title: "Browser Caching",
    description:
      "How long browsers can store files before re-downloading. Longer cache times mean faster repeat visits.",
  },
  "cookie-count": {
    title: "Cookie Count",
    description:
      "Number of cookies set by the site. Fewer cookies means less data sent with every request, improving performance.",
  },
  redirects: {
    title: "Redirects",
    description:
      "Each redirect adds an extra round-trip to the server, delaying the page load. Zero redirects is ideal.",
  },
  "page-size": {
    title: "Total Page Size",
    description:
      "The uncompressed size of all resources. Smaller pages load faster, especially on slow connections.",
  },
  "transfer-size": {
    title: "Transfer Size",
    description:
      "Actual bytes transferred over the network (after compression). This is what users actually download.",
  },
  "green-hosting": {
    title: "Green Hosting",
    description:
      "Whether the web host uses renewable energy. Green hosting reduces the carbon footprint of your website.",
  },
  "co2-per-view": {
    title: "CO₂ per Page View",
    description:
      "Carbon emissions generated by one page load, including data center, network, and device energy usage.",
  },
};

// Initialize popup
document.addEventListener("DOMContentLoaded", async () => {
  try {
    // Get current tab
    const [tab] = await chrome.tabs.query({
      active: true,
      currentWindow: true,
    });

    if (!tab || !tab.url) {
      showEmptyState("Unable to access this page");
      return;
    }

    // Skip chrome:// and extension pages
    if (
      tab.url.startsWith("chrome://") ||
      tab.url.startsWith("chrome-extension://")
    ) {
      showEmptyState("Cannot analyze browser internal pages");
      return;
    }

    const domain = new URL(tab.url).hostname;
    const key = STORAGE_PREFIX + domain;

    // Load analysis from storage
    const result = await chrome.storage.local.get(key);

    if (result[key]) {
      currentAnalysis = result[key];

      // Check if expired
      if (currentAnalysis.expiresAt && Date.now() > currentAnalysis.expiresAt) {
        showEmptyState("Analysis expired. Run new analysis in DevTools.");
        return;
      }

      // Display the analysis
      displayAnalysis(currentAnalysis);
    } else {
      showEmptyState(
        "No analysis found. Open DevTools → Globemallow tab to analyze.",
      );
    }

    // Setup button listeners
    setupButtons();

    // Setup collapsible sections
    setupCollapsibleSections();

    // Setup metric click handlers
    setupMetricClickHandlers();
  } catch (error) {
    console.error("Popup initialization error:", error);
    showEmptyState("Error loading analysis data");
  }
});

// Display analysis in existing HTML
function displayAnalysis(analysis) {
  const data = analysis.auditData;

  // Update summary cards
  updateElement("summaryGrade", data.finalGrade || "—");
  updateElement("summaryScore", data.finalScore || "—");
  updateElement(
    "summaryCO2",
    analysis.co2Total ? `${analysis.co2Total}g` : "—",
  );

  // Update all metrics with data-metric attributes
  updateAllMetrics(data, analysis);
}

// Update all metrics in the DOM
function updateAllMetrics(data, analysis) {
  // Performance metrics
  updateMetric("fcp", data.loadTimeChart, "s");
  updateMetric("lcp", data.duration, "s");
  updateMetric("tbt", 0.05, ""); // Placeholder
  updateMetric("cls", 0.1, ""); // Placeholder

  // Image metrics
  updateMetric("lazy-loading", data.lazyLoadChart, "%");
  updateMetric("modern-images", data.svgChart, "%");
  updateMetric("responsive-images", data.resImgChart, "%");
  updateMetric(
    "image-compression",
    `${data.imgCompressKBSaved} KB`,
    "could be saved",
  );

  // Code metrics
  updateMetric("bundle-size", data.jsSizeLab || "—", "");
  updateMetric("unused-js", `${data.unusedJSKB} KB`, "unused");
  updateMetric("css-usage", data.percentCSS, "%");
  updateMetric("third-party-scripts", data.thirdPartyScripts || "—", "");

  // Best practices
  updateMetric("gzip", data.gzipEnabled ? "✓ enabled" : "✗ disabled", "");
  updateMetric(
    "minification",
    data.minificationEnabled ? "✓ enabled" : "✗ not optimized",
    "",
  );
  updateMetric("https", data.httpsEnabled ? "✓ secure" : "✗ not secure", "");
  updateMetric("browser-caching", "30 days", ""); // Placeholder
  updateMetric("cookie-count", data.cookieMax || "—", "");
  updateMetric("redirects", data.redirectsax || "0", "found");

  // Sustainability metrics
  updateMetric("page-size", data.sizeLabel || "—", "");
  updateMetric("transfer-size", data.transferLabel || "—", "");
  updateMetric(
    "green-hosting",
    analysis.greenHosting ? "✓ renewable energy" : "✗ standard hosting",
    "",
  );
  updateMetric(
    "co2-per-view",
    analysis.co2Total ? `${analysis.co2Total}g` : "—",
    "",
  );

  // Update impact section values
  updateImpactSection(data, analysis);
}

// Update a specific metric by data-metric attribute
function updateMetric(metricId, value, suffix = "") {
  const element = document.querySelector(`[data-metric="${metricId}"]`);
  if (!element) return;

  const valueEl = element.querySelector(".audit-item-value");
  if (valueEl && value !== undefined && value !== null) {
    const displayValue = typeof value === "number" ? value.toFixed(2) : value;
    valueEl.textContent = displayValue;

    const unitEl = element.querySelector(".audit-item-unit");
    if (unitEl && suffix) {
      unitEl.textContent = suffix;
    }
  }
}

// Update impact section
function updateImpactSection(data, analysis) {
  const impactItems = document.querySelectorAll(".impact-item");

  if (impactItems[0]) {
    const valueEl = impactItems[0].querySelector(".impact-value");
    if (valueEl)
      valueEl.textContent = analysis.co2Total ? `${analysis.co2Total}g` : "—";
  }

  if (impactItems[1]) {
    const valueEl = impactItems[1].querySelector(".impact-value");
    if (valueEl)
      valueEl.textContent = analysis.kwhTotal
        ? `${analysis.kwhTotal.toFixed(4)} kWh`
        : "—";
  }

  if (impactItems[2]) {
    const valueEl = impactItems[2].querySelector(".impact-value");
    const savings = analysis.co2Total
      ? (analysis.co2Total * 0.25).toFixed(1)
      : 0;
    if (valueEl) valueEl.textContent = `-${savings}g CO₂`;
  }

  if (impactItems[3]) {
    const valueEl = impactItems[3].querySelector(".impact-value");
    const monthly = analysis.co2Total
      ? ((analysis.co2Total * 5000) / 1000).toFixed(1)
      : 0;
    if (valueEl) valueEl.textContent = `${monthly} kg`;
  }
}

// Setup metric click handlers
function setupMetricClickHandlers() {
  const metrics = document.querySelectorAll("[data-metric]");

  metrics.forEach((metric) => {
    metric.style.cursor = "pointer";

    metric.addEventListener("click", () => {
      const metricId = metric.getAttribute("data-metric");
      const explanation = METRIC_EXPLANATIONS[metricId];

      if (explanation) {
        updateMetricDetail(explanation.title, explanation.description);
      }
    });
  });
}

// Update metric detail panel
function updateMetricDetail(title, description) {
  const metricTitle = document.getElementById("metricTitle");
  const metricBody = document.getElementById("metricBody");

  if (metricTitle) metricTitle.textContent = title;
  if (metricBody) metricBody.textContent = description;
}

// Setup button listeners
function setupButtons() {
  const exportBtn = document.getElementById("exportBtn");
  const optimizationsBtn = document.getElementById("optimizationsBtn");
  const openDevToolsBtn = document.getElementById("openDevToolsBtn");

  if (exportBtn) {
    exportBtn.addEventListener("click", exportReport);
  }

  if (optimizationsBtn) {
    optimizationsBtn.addEventListener("click", openOptionsPage);
  }

  if (openDevToolsBtn) {
    openDevToolsBtn.addEventListener("click", () => {
      alert(
        "To analyze this site:\n\n" +
          "1. Open DevTools (F12 or right-click → Inspect)\n" +
          "2. Go to the 'Globemallow' tab\n" +
          "3. Click 'Analyze Page'",
      );
    });
  }
}

// Open options page
function openOptionsPage() {
  chrome.runtime.openOptionsPage();
}

// Export report
async function exportReport() {
  if (!currentAnalysis) {
    alert("No analysis data to export");
    return;
  }

  try {
    const report = generateReport(currentAnalysis);

    // Create and download file
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `globemallow-report-${currentAnalysis.domain}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    // Show success feedback
    const exportBtn = document.getElementById("exportBtn");
    const originalText = exportBtn.textContent;
    exportBtn.textContent = "✅ Exported!";
    setTimeout(() => {
      exportBtn.textContent = originalText;
    }, 2000);
  } catch (error) {
    console.error("Export error:", error);
    alert("Failed to export report");
  }
}

// Generate report text
function generateReport(analysis) {
  const data = analysis.auditData;
  const timestamp = new Date(analysis.timestamp).toLocaleString();

  return `
═══════════════════════════════════════════════════════
  GLOBEMALLOW WEB SUSTAINABILITY AUDIT REPORT
═══════════════════════════════════════════════════════

Generated: ${timestamp}
URL: ${analysis.url}
Domain: ${analysis.domain}

───────────────────────────────────────────────────────
OVERALL SUMMARY
───────────────────────────────────────────────────────
Grade:           ${data.finalGrade || "N/A"}
Score:           ${data.finalScore || "N/A"}/100
CO₂ per View:    ${analysis.co2Total || "N/A"}g
Energy Usage:    ${analysis.kwhTotal ? analysis.kwhTotal.toFixed(6) : "N/A"} kWh
Page Size:       ${data.sizeLabel || "N/A"}
Transfer Size:   ${data.transferLabel || "N/A"}

───────────────────────────────────────────────────────
PERFORMANCE METRICS
───────────────────────────────────────────────────────
Load Time:       ${data.duration ? data.duration.toFixed(2) : "N/A"}s
First Paint:     ${data.loadTimeChart ? data.loadTimeChart.toFixed(2) : "N/A"}s

───────────────────────────────────────────────────────
RESOURCE ANALYSIS
───────────────────────────────────────────────────────
JavaScript:      ${data.jsSizeLab || "N/A"}
Unused JS:       ~${data.unusedJSKB || 0} KB
CSS Usage:       ${data.percentCSS || "N/A"}%
Third-party:     ${data.thirdPartyScripts || "N/A"} scripts

───────────────────────────────────────────────────────
IMAGE OPTIMIZATION
───────────────────────────────────────────────────────
Lazy Loading:    ${data.lazyLoadChart || "N/A"}%
Modern Formats:  ${data.svgChart || "N/A"}%
Responsive:      ${data.resImgChart || "N/A"}%
Savings:         ${data.imgCompressKBSaved || "N/A"} KB possible

───────────────────────────────────────────────────────
BEST PRACTICES
───────────────────────────────────────────────────────
HTTPS:           ${data.httpsEnabled ? "✓ Enabled" : "✗ Not enabled"}
Compression:     ${data.gzipEnabled ? "✓ Enabled" : "✗ Disabled"}
Minification:    ${data.minificationEnabled ? "✓ Enabled" : "✗ Not optimized"}

───────────────────────────────────────────────────────
SUSTAINABILITY
───────────────────────────────────────────────────────
Green Hosting:   ${analysis.greenHosting === true ? "✓ Yes" : analysis.greenHosting === false ? "✗ No" : "Unknown"}
Monthly Impact:  ~${(((analysis.co2Total || 0) * 5000) / 1000).toFixed(1)} kg CO₂ (5,000 views)

───────────────────────────────────────────────────────
RECOMMENDATIONS
───────────────────────────────────────────────────────
${generateRecommendations(data, analysis)}

═══════════════════════════════════════════════════════
Generated by Globemallow - Web Sustainability Tool
═══════════════════════════════════════════════════════
`;
}

// Generate recommendations
function generateRecommendations(data, analysis) {
  const recommendations = [];
  let priority = 1;

  if (data.imgCompressKBSaved > 100) {
    recommendations.push(
      `${priority++}. Optimize images (save ~${data.imgCompressKBSaved} KB)`,
    );
  }

  if (parseFloat(data.lazyLoadChart) < 50) {
    recommendations.push(`${priority++}. Implement lazy loading for images`);
  }

  if (parseFloat(data.svgChart) < 40) {
    recommendations.push(`${priority++}. Convert images to WebP/AVIF format`);
  }

  if (data.unusedJSKB > 50) {
    recommendations.push(
      `${priority++}. Remove unused JavaScript (~${data.unusedJSKB} KB)`,
    );
  }

  if (!data.gzipEnabled) {
    recommendations.push(`${priority++}. Enable compression (gzip/brotli)`);
  }

  if (!data.minificationEnabled) {
    recommendations.push(`${priority++}. Minify JavaScript and CSS files`);
  }

  if (data.duration > 3) {
    recommendations.push(
      `${priority++}. Improve load time (currently ${data.duration.toFixed(1)}s)`,
    );
  }

  if (analysis.greenHosting === false) {
    recommendations.push(`${priority++}. Consider green hosting provider`);
  }

  if (recommendations.length === 0) {
    return "   ✓ Great work! Site is well-optimized.";
  }

  return recommendations.map((r) => `   ${r}`).join("\n");
}

// Setup collapsible sections
function setupCollapsibleSections() {
  const headers = document.querySelectorAll(".section-header");

  headers.forEach((header) => {
    header.addEventListener("click", () => {
      const section = header.closest(".audit-section");
      section.classList.toggle("open");
      header.classList.toggle("open");
    });
  });
}

// Show empty state
function showEmptyState(message) {
  // Clear all summary values
  updateElement("summaryGrade", "—");
  updateElement("summaryScore", "—");
  updateElement("summaryCO2", "—");

  // Clear all metric values
  clearAllMetrics();

  // Clear impact section
  clearImpactSection();

  // Update metric detail area with message
  const metricTitle = document.getElementById("metricTitle");
  const metricBody = document.getElementById("metricBody");

  if (metricTitle) metricTitle.textContent = "No Analysis Available";
  if (metricBody) metricBody.textContent = message;

  // Hide/show appropriate buttons
  const exportBtn = document.getElementById("exportBtn");
  const optimizationsBtn = document.getElementById("optimizationsBtn");
  const openDevToolsBtn = document.getElementById("openDevToolsBtn");

  if (exportBtn) exportBtn.style.display = "none";
  if (optimizationsBtn) optimizationsBtn.style.display = "none";
  if (openDevToolsBtn) openDevToolsBtn.style.display = "flex";
}

// Clear all metric values
function clearAllMetrics() {
  const allMetrics = document.querySelectorAll("[data-metric]");

  allMetrics.forEach((metric) => {
    const valueEl = metric.querySelector(".audit-item-value");
    if (valueEl) valueEl.textContent = "—";

    const unitEl = metric.querySelector(".audit-item-unit");
    if (unitEl) unitEl.textContent = "";
  });
}

// Clear impact section
function clearImpactSection() {
  const impactItems = document.querySelectorAll(".impact-item");

  impactItems.forEach((item) => {
    const valueEl = item.querySelector(".impact-value");
    if (valueEl) valueEl.textContent = "—";
  });
}

// Helper to update element text
function updateElement(id, text) {
  const el = document.getElementById(id);
  if (el) el.textContent = text;
}
